# Site settings
title: Extempore docs
email: extemporelang@googlegroups.com
description: >
  Extempore programming language documentation

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://extemporelang.github.io
git_address: https://github.com/extemporelang/extemporelang.github.io
git_edit_address: https://github.com/extemporelang/extemporelang.github.io/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Canberra/Australia
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
